[package]
name = "msys2-gtk-packager"
version = "0.0.0"
edition = "2021"

[dependencies]
anyhow = "1.0.65"
argh = "0.1.9"
bitflags = "1.3.2"
cargo_metadata = "0.15.0"
goblin = { version = "0.5.4", features = [ "std", "pe32", "pe64" ], default-features = false }
walkdir = "2.3.2"
