[package]
name = "msys2-gtk-packager"
version = "0.0.0"
edition = "2021"

[dependencies]
anyhow = "1.0.66"
argh = "0.1.9"
camino = "1.1.1"
cargo_metadata = "0.15.0"
msys2 = { path = "../msys2" }
msys2-packager = { path = "../msys2-packager" }
walkdir = "2.3.2"
